server:
#  port: 8888
  port: 80
  contextPath: /
spring:
  jpa:
    database: MYSQL
#    database: ORACLE
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/pch
    username: root
    password: 1234
#    url: jdbc:oracle:thin:@10.169.4.33:5001:dspdb
#    username: econe
#    password: password