server:
  port: 80
#  port: 8888
  contextPath: /
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  aop:
    auto: true
  jpa:
#    database: MYSQL
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:mysql://localhost:3306/pch
#    username: root
#    password: 1234
    url: jdbc:oracle:thin:@10.169.4.33:5001:dspdb
    username: econe
    password: password