server:
#  port: 80
  port: 8080
  contextPath: /
spring:
  profiles:
    active: config
  mail:
    default-encoding: UTF-8
    host: 10.163.134.180
    port: 25
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  aop:
    auto: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/pch
    username: root
    password: 1234
logging:
  file:
    study.log